### PR TITLE
:sparkles: add compose vs engine version check

### LINKED ISSUE #11: Check docker compose version against docker engine
The app should check the docker compose version versus the docker engine version before deploying.
Otherwise unexpected behavior can happen.
Compatibility is mentioned here:
https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix

We should maybe check the api version versus engine version. Here is the mapping:

https://docs.docker.com/develop/sdk/#api-version-matrix

### PR DESCRIPTION
**Pull request by OlivierCuyp**
Please comment already ...
This should resolve #11

### CODE REVIEW

**Comment by OlivierCuyp** [comment]
I'm still wondering if I should cache the Docker Engine version or not.
And also, this version could differ between nodes.
So depending on which proxy you ask the answer might be different... How do we handle that ?

**Comment by nekuz0r** [comment]
@OlivierCuyp 

I think we should retrieve the list of all nodes in the swarm cluster, get the version of the docker engine for each of them, then take the lowest one as reference.

It should then cache it for some times before repeating the procedure (on demand).

**Comment by OlivierCuyp** [comment]
@nekuz0r I'm wondering too where to place the code doing this...
I don't think it really belongs to the DockerApi lib. Maybe more to the Swarm controller since this touch definition and docker api.

**Comment by OlivierCuyp** [comment]
@nekuz0r could check the new commit. It still missing the cashing but I think this is cleaner...

File: src/controllers/swarm/main.ts [hunk 1]
```diff
@@ -25,6 +27,21 @@ export async function deploy(
   force: boolean = false
 ): Promise<string> {
   const definition = await opsSvc.getDefinition(definitionName)
+  const nodesInfo = await swarmSvc.listNodes()
```
Comment (nekuz0r) [inline src/controllers/swarm/main.ts]: `const nodes = ...`

File: src/helpers/composeVersionChecker.ts [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+  '1.20': '1.8',
+  '1.19': '1.7',
+  '1.18': '1.6',
+}
+
+function normalizeComposeVersion(composeVersion: string): string {
+  return composeVersion.replace(/^(\d+)$/, '$1.0')
+}
+
+function cleanEngineVersion(baseEngineVersion: string): string {
```
Comment (nekuz0r) [inline src/helpers/composeVersionChecker.ts]: Since the compose version of this function is called `normalizeComposeVersion` shouldn't this one called `normalizeEngineVersion` ?

File: src/helpers/composeVersionChecker.ts [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+  return baseEngineVersion.replace(/-(ce|ee)$/, '')
+}
+
+function getMinimalEngineVersion(nodesInfo: Array<any>): string {
```
Comment (nekuz0r) [inline src/helpers/composeVersionChecker.ts]: `nodesInfo` => `nodes`
`nodeInfo` => `node`

File: src/helpers/composeVersionChecker.ts [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+  return nodesInfo.reduce((lowestEngineVersion: string, nodeInfo: any) => {
+    const nodeEngineVersion: string = cleanEngineVersion(
+      nodeInfo.Description.Engine.EngineVersion
+    )
+    if (
+      !lowestEngineVersion ||
+      compareVersions(nodeEngineVersion, lowestEngineVersion) < 0
+    ) {
+      lowestEngineVersion = nodeEngineVersion // eslint-disable-line no-param-reassign
```
Comment (nekuz0r) [inline src/helpers/composeVersionChecker.ts]: No need to reassign, simply return `nodeEngineVersion`, since it inside a reduce, the returned value will automatically be assigned to it.

File: src/helpers/composeVersionChecker.ts [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+  apiVersion?: string
+) {
+  const nComposeVersion = normalizeComposeVersion(composeVersion)
+  const minimalEngineVersion: string = composeVersionMap[nComposeVersion]
+  if (!minimalEngineVersion) {
+    throw new Error(`Unknown Docker Compose ${composeVersion}`)
+  }
+  const actualEngineVersion = getMinimalEngineVersion(nodesInfo)
+
+  let calculatedEngineVersion = ''
```
Comment (nekuz0r) [inline src/helpers/composeVersionChecker.ts]:
```
if (!apiVersion) {
  return compareVersions(actualEngineVersion, minimalEngineVersion) >= 0
}

const highestEngineVersion = apiVersionMap[apiVersion]
if (compareVersions(actualEngineVersion, highestEngineVersion) < 0) {
  return actualEngineVersion
}

return highestEngineVersion
```

File: src/libs/DockerApi.ts [hunk 6]
```diff
@@ -101,6 +103,10 @@ export default class DockerApi {
     return request(requestOptions)
   }
 
+  getVersion() {
```
Comment (nekuz0r) [inline src/libs/DockerApi.ts]: Make the property `version`public and readonly, thus this getter is not required anymore.
`private version: string` => `public readonly version: string`

File: src/helpers/composeVersionChecker.ts [hunk 7]
```diff
@@ -0,0 +1,103 @@
+import compareVersions from 'compare-versions'
+
+interface IVersionMap {
+  [key: string]: string
+}
+
+// Here the engine version is the lowest needed to support all docker compose features
+const composeVersionMap: IVersionMap = {
```
Comment (nekuz0r) [inline src/helpers/composeVersionChecker.ts]: use a JSON file to store these mappings and enable `resolveJsonModule` typescript option. (may require `esModuleInterop` and/or `allowSyntheticDefaultImports`

**Review by nekuz0r — CHANGES_REQUESTED** [review]

**Review by nekuz0r — APPROVED** [review]
